server:
  port: 8080
spring:
  application:
    name: opendarts-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:opendarts_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET:181bffe5afd4b7d3cbeb58345477e004b6325064e06b77610339809634ce7352}

autoscore:
  port: ${AUTOSCORE_PORT:8765}
  host: ${AUTOSCORE_HOST:localhost}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
