version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: multidart-postgres
    environment:
      POSTGRES_DB: multidart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - multidart-network
    restart: unless-stopped

networks:
  multidart-network:
    driver: bridge

volumes:
  postgres_data:
