server:
  port: 8080
  # Configure max HTTP post size for large WebSocket handshakes
  max-http-header-size: 16KB
  tomcat:
    max-http-post-size: 10MB

spring:
  application:
    name: api-gateway
  # WebSocket configuration
  websocket:
    max-text-message-buffer-size: 10485760  # 10MB in bytes
    max-binary-message-buffer-size: 10485760  # 10MB in bytes

  datasource:
    url: jdbc:postgresql://localhost:5432/opendarts_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 181bffe5afd4b7d3cbeb58345477e004b6325064e06b77610339809634ce7352

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs